CREATE TABLE BOOK_CONTENT
(
    BOOK_ID         varchar  NOT NULL PRIMARY KEY,
    CONTENT_BOOK_ID varchar  NOT NULL,
    CREATED_DATE    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    FOREIGN KEY (CONTENT_BOOK_ID) REFERENCES BOOK (ID),
    CHECK (BOOK_ID <> CONTENT_BOOK_ID)
);

CREATE INDEX BOOK_CONTENT_CONTENT_BOOK_ID_IDX ON BOOK_CONTENT (CONTENT_BOOK_ID);
