<template><v-dialog v-model="modal" max-width="520"><v-card><v-card-title>{{ $t('dialog.move_series.title') }}</v-card-title><v-card-text><v-select v-model="targetLibraryId" :items="libraryOptions" :label="$t('dialog.move_series.target_library')" /></v-card-text><v-card-actions><v-spacer/><v-btn text @click="modal = false">{{ $t('common.cancel') }}</v-btn><v-btn color="primary" text :disabled="!targetLibraryId" :loading="moving" @click="moveSeries">{{ $t('dialog.move_series.confirm') }}</v-btn></v-card-actions></v-card></v-dialog></template>
<script lang="ts">
import Vue from 'vue'
import {SeriesDto} from '@/types/komga-series'
import {LibraryDto} from '@/types/komga-libraries'
import {BookSearch, SearchConditionSeriesId, SearchOperatorIs} from '@/types/komga-search'
import {ERROR} from '@/types/events'
export default Vue.extend({name: 'MoveSeriesDialog', props: {value: Boolean, series: {type: Array as () => SeriesDto[], required: true}}, data: () => ({targetLibraryId: null as string | null, moving: false}), computed: {modal: {get(): boolean { return this.value }, set(value: boolean) { this.$emit('input', value); if (!value) this.targetLibraryId = null }}, libraryOptions(): {text: string, value: string}[] { const source = new Set(this.series.map(s => s.libraryId)); return (this.$store.getters.getLibraries as LibraryDto[]).filter(l => !source.has(l.id)).map(l => ({text: l.name, value: l.id})) }}, methods: {async moveSeries() { if (!this.targetLibraryId) return; this.moving = true; try { const pages = await Promise.all(this.series.map(s => this.$komgaBooks.getBooksList({condition: new SearchConditionSeriesId(new SearchOperatorIs(s.id))} as BookSearch, {size: 10000} as PageRequest))); const books = pages.flatMap(p => p.content); await this.$komgaBooks.moveBooks(books.map(b => b.id), this.targetLibraryId); this.$emit('moved'); this.modal = false } catch (e) { this.$eventHub.$emit(ERROR, {message: e.message}) } finally { this.moving = false }}}})
</script>
